#include<iostream>
#include<unistd.h>
#include<signal.h>
#include<sys/wait.h>
using namespace std;

void Signal_handler(int signum){
    cout<<"In signal handler Function Generated by Child "<<endl;
    cout<<"Signal Generated with Id: "<<signum<<endl;
}

int main(){
    if(signal(SIGCHLD,Signal_handler) == SIG_ERR){
        perror("Signal Not successfully initialized");
        exit(EXIT_FAILURE);
    }
    pid_t id;
    id = fork();
    if(id < 0) exit(EXIT_FAILURE);
    if( id == 0){
        cout<<"IN child Process"<<endl;
    }
    wait(NULL);
    cout<<"In Parent Process"<<endl;
    return 0;
}